# Generated by Django 5.2.1 on 2025-06-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_ticket_motivo_anulacion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_column='sucursalid_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='soporte.sucursal', verbose_name='Sucursal'),
        ),
    ]
