# Generated by Django 5.2.1 on 2025-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Si es True, el usuario debe cambiar la contraseña en su próximo inicio de sesión.'),
        ),
    ]
