# Generated by Django 5.2.1 on 2025-06-13 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Problema',
                'verbose_name_plural': 'Categorías de Problema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Ticket',
                'verbose_name_plural': 'Estados de Ticket',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre de la Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del problema')),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de error')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='problemas_comunes/', verbose_name='Imagen de error')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='soporte.categoriaproblema', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Problema Común',
                'verbose_name_plural': 'Problemas Comunes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen_error', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Imagen del error')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soporte.estadoticket', verbose_name='Estado')),
                ('sucursal', models.ForeignKey(db_column='sucursalid_ticket', on_delete=django.db.models.deletion.PROTECT, to='soporte.sucursal', verbose_name='Sucursal del ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
