# Generated by Django 5.2.1 on 2025-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de anulación'),
        ),
    ]
