# Generated by Django 5.2.1 on 2025-06-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_ticket_motivo_anulacion'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='ticket',
            name='usuario_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IP del usuario'),
        ),
    ]
